### ISSUE TITLE
Pull in updated curation_concerns styles

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/heliotrope#143] opened 2016-04-11 14:34 UTC
**DESCRIPTION**
Curations Concerns has been updated to use a more 'vanilla' bootstrap theme that should have better responsive behavior (and therefore display more consistently across browsers & resolutions)

**ACTION**
Generate a new curation_concerns application and copy styles from that to heliotrope.

**Comment by acozine** [comment] 2016-04-11 14:47
This should enable us to close #136.

**Comment by val99erie** [comment] 2016-04-15 14:54
I'm going to close this story as a duplicate of 141.  All the styles are imported directly from curation_concerns, so there aren't any styles to copy over.

**Closed by val99erie** 2016-04-15 14:54 UTC
Labels: ready
